const imgUrl ={
eye:require('../assets/Images/eye.png'),
arrowright:require('../assets/Images/rightarrow.png'),
uberlogo:require('../assets/Images/uber.png'),
lyftlogo:require('../assets/Images/Vector.png'),
caricon:require('../assets/Images/caricon.png'),
uber_proof:require('../assets/Images/proofuber.png'),
resendemail:require('../assets/Images/resendemail.png'),
filterimg:require('../assets/Images/filterimg.png'),
Mercedes:require('../assets/Images/Mercedes.png'),
Silver:require('../assets/Images/silver.png'),
Gas:require('../assets/Images/gas.png'),
Star:require('../assets/Images/star.png'),
Back_icon:require('../assets/Images/backicon.png'),
tabCar:require('../assets/Images/carVector.png'),
tabkey:require('../assets/Images/fi-ss-key.png'),
tabperform:require('../assets/Images/fi-ss-megaphone.png'),
tabUser:require('../assets/Images/fi-sr-user.png'),
tabsettings:require('../assets/Images/fi-sr-settings.png'),
addButton:require('../assets/Images/Icon_button.png'),
Most_Popular_sticker:require('../assets/Images/sticker.png'),
Ellipse:require('../assets/Images/Ellipse.png'),
Genralicon:require('../assets/Images/genralicon.png'),
PartnershipIcon:require('../assets/Images/PartnershipIcon.png'),
Headseticon:require('../assets/Images/headset.png'),
Hearticon:require('../assets/Images/heart.png'),

redCar:require('../assets/Images/carred.png'),
greyCar:require('../assets/Images/cargrey.png'),
onedot:require('../assets/Images/onedot.png'),
threedot:require('../assets/Images/threedot.png'),
}

export default imgUrl