export const Texts = {
  Email: 'Email',
  Enter_Email: 'Enter your email',
  Enter_Password: 'Create a password',
  Password: 'Password',
  Rememberme: 'Remember me',
  Next: 'Next',
  Or: 'Or',
  continue_with_uber: 'Continue with Uber',
  continue_with_Lyft: 'Continue with Lyft',
  Forgot_pass: 'Forgot password?',
  not_account: 'Do not have an accout?',
  Sign_Up: 'Sign Up',
  Sign_IN: 'Sign In',
  First_name: 'First Name',
  Last_name: 'Last Name',
  Repeat_password: 'Repeat password',
  Enter_last_name: 'Enter your last name',
  Enter_f_N: 'Enter your first name',
  Enter_R_Pass: 'Repeat a password',
  Sig_Up: 'Sign Up',
  i_agree: 'I agree with the ',
  Terms: 'Terms',
  and: ' and ',
  Policy: 'Privacy Policy',
  Already_Account: 'Already have an account? ',
  Login: 'Login',
  Verification: 'Verification',
  Add_Driver_license: 'Please, add your driver license',
  Add_Proof_uber: '& proof of your Uber account',
  Driver_License: 'Driver License',
  Uber_Proof: 'Uber Proof',
  ForgotPassword: 'Forgot Password?',
  Forgot_pass_intructions: 'Enter your email and we will email intructions on ',
  How_to_reset: 'how to reset your password.',
  Back_to: 'Back to ',
  Link_sent: 'Link has been sent',
  A_Link_Has_BEen_sent: 'A link to reset password has been sent',
  To_Yur_emal: 'to your email.',
  Resend_email_link: 'Resend email link',
  car_availible: '28 cars availiable',
  Filters: 'Filters',
  Mercedes: 'Mercedes-Benz-E-Class 2014',
  Seats: '5 seats | 4 doors',
  Silver: 'Silver',
  Rating: '4.9 (121 trips)',
  Gas: 'Gas',
  View: 'View',
  Details: 'Details',
  car_Features:
    'AUX Input, Backup camera, Blind spot warning, Bluetooth, Heated seats, Sunroof, USB input.',
  Features: 'Features',
  Description: 'Description',
  Choose: 'Choose',
  car_Description:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur.',
    Monthly_plan:'Monthly plan',
    Select_monthly_plan: 'Select your monthly plan',
    Insurance_included: 'Insurance included. Change plans anytime.',
    Pay_you:'Pay as you go',
    five_hundred_Miles:'500 Miles',
    eight_five_zero:'850 Miles',
    one_two_zero:'1200 Miles',
    two_nine_four:'$294',
    four_six_nine:'$469',
    five_six_nine:'$569',
    six_six_nine:'$669',
month:'/month',
Auto_renews:'Auto-renews 200 miles at $0.45/mi',
four_five_Overage:'Overage miles: $0.45/mi',
three_five_Overage:'Overage miles: $0.35/mi',
two_five_Overage:'Overage miles: $0.25/mi',
Continue_to_schedule:'Continue to schedule',
Keys:"Keys",
General:'General',
Partnership_Benefits:'Partnership Benefits',
Support_Assistance:'Support and Assistance',
About_SwiftRide:'About SwiftRide',
My_Profile:'My Profile',
User_name:'Michael Rodrigez',
Personal_Information:'Personal Information',
Subscription :'Subscription',
Payment_Info:'Payment Info',
Change_Password:'Change Password',
Performance:'Performance',
Rate:'Rate:',
Miles:'Miles:',
Score:'Score:',
four_saven:'4.7',
eight_eight:'88',
three_four_five:'345',
Upcoming_return:'Upcoming return',
Date:'Date',
Time:'Time',
Address:'Address',
Tue_Oct:'Tue, Oct 24',
Two_Pm:'2:00 PM - 3:00 PM',
San_Mateo:'San Mateo, CA 94401',
Change_return_location_time:'Change return location or time',
Cancel_return:'Cancel your return',
Current_Usage:'Current Usage',
Miles_Driven:"Miles Driven",
Billing_Cycle:'Billing Cycle',
Stats:'Stats',
five_sevan_miles:'57 miles (as of Oct 8 at 6:25 PM)',
Billing_cycle_detail:'Mon, October 10 - Sun, October 16',
Phone_Usage:'Phone Usage',
Braking:'Braking',
Speeding:'Speeding',
Acceleration:'Acceleration',
ninty:'90',
seventy:'70',
six_eight:'68',
four_six:'46',
Pending_Tasks:'Pending Tasks',
Change_Machine_Oil:'Change Machine Oil',
Mark_done:'Mark as done',
Date_of_birth:'Date of birth',
Telephone:'Telephone',
Drivers_license_check:'Drivers license check',
Credit_Check:'Credit Check',
tele_num:'+ 123 456 09700',
mail_com:'mail@mail.com',
D_O_B:'10.02.1996',
L_name:'Rodrigez',
F_name:'Michael',
Edit:'Edit',
Documents:'Documents',
one_MB:'1.0 MB',
five_hundred:'500 Miles',
Renew_date:'Renew 12.03.2024',
Manage:'Manage',
Upgrade:'Upgrade',
Pick_Up:'Pick Up',
Choose_date_pick:'Choose date and place to pick up SwiftRide car',
You_will_have_get_car:'You will have 24 hours to get the car.',
pm_two_time:'2:00 PM - 3:00 PM',
Change:'Change',
Checkout:'Checkout',
Enter_Current_Password:'Enter Current Password',
Create_New_Password:'Create New Password',
Confirm_New_Password:'Confirm New Password',
Create_a_password:'Create a password',
Save:'Save',
Notifications:'Notifications',
Biometric_settings:'Biometric settings',
Enable_biometric:'Enable biometric login',
Qualify_free_Services:'Qualify for free Services',
Information_Partners:'Information from Partners',
Referral_programs:'Referral programs',
Support_Chat:'Support Chat',
FAQ:'FAQ',
About_Swift_Ride:'About Swift Ride',
Version:'Version',
Build:'Build',
Privacy_and_policy:'Privacy and policy',
Terms_of_use:'Terms of use',
Rate_Us:'Rate Us',
build_num:'109323.230459',
version_num:'1.11 (12)',
Dummy_Text:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
Plan:'Plan',
Trip_fee:'Trip fee',
trip_fee_dollar:'$20.00',
Total:'Total',
four_eight_nine:'$489.00',
Gift_Card:'Gift Card',
Promo_Code:'Promo Code',
Add_another_card:'Add another card',
Add:'Add',
Pay:'Pay',
three_four_nine_zero:'(3490)',
Default:'Default',
Faiz_Anwar:'Faiz Anwar',
num_mastar_card:'4556 - 5642 - 0695 - 3490',
Zayn_Malik:'Zayn Malik',
visa_num:'5142 - 8164 - 6526 - 2563',
Add_Card:'Add Card',
Cardholder:'Cardholder',
ZIP_Code:"ZIP Code",
Card_Number:"Card Number",
one_two_three:'1234 1234 1234 1234',
Expire_Date:"Expire Date",
MM_YYYY:'MM/YYYY',
CVV:'CVV',
Make_card_default:'Make this card default',
Payment_succesful :"Payment is succesful!",
Car_reserved:'Car is reserved!',
Now_documents_your_Uber:'Now you need to upload these documents to your Uber account',
dummy_txt_second:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.',
Insurance_pdf:'Insurance.pdf',
Registration_pdf:'Registration.pdf',
Once_confirmation_receive_Uber:'Once we receive confirmation from Uber we will sent you keys',
Got_it:"Got it!",


}
