export const Texts = {
  Email: 'Email',
  Enter_Email: 'Enter your email',
  Enter_Password: 'Create a password',
  Password: 'Password',
  Rememberme: 'Remember me',
  Next: 'Next',
  Or: 'Or',
  continue_with_uber: 'Continue with Uber',
  continue_with_Lyft: 'Continue with Lyft',
  Forgot_pass: 'Forgot password?',
  not_account: 'Do not have an accout?',
  Sign_Up: 'Sign Up',
  Sign_IN: 'Sign In',
  First_name: 'First name',
  Last_name: 'Last name',
  Repeat_password: 'Repeat password',
  Enter_last_name: 'Enter your last name',
  Enter_f_N: 'Enter your first name',
  Enter_R_Pass: 'Repeat a password',
  Sig_Up: 'Sign Up',
  i_agree: 'I agree with the ',
  Terms: 'Terms',
  and: ' and ',
  Policy: 'Privacy Policy',
  Already_Account: 'Already have an account? ',
  Login: 'Login',
  Verification: 'Verification',
  Add_Driver_license: 'Please, add your driver license',
  Add_Proof_uber: '& proof of your Uber account',
  Driver_License: 'Driver License',
  Uber_Proof: 'Uber Proof',
  ForgotPassword: 'Forgot Password?',
  Forgot_pass_intructions: 'Enter your email and we will email intructions on ',
  How_to_reset: 'how to reset your password.',
  Back_to: 'Back to ',
  Link_sent: 'Link has been sent',
  A_Link_Has_BEen_sent: 'A link to reset password has been sent',
  To_Yur_emal: 'to your email.',
  Resend_email_link: 'Resend email link',
  car_availible: '28 cars availiable',
  Filters: 'Filters',
  Mercedes: 'Mercedes-Benz-E-Class 2014',
  Seats: '5 seats | 4 doors',
  Silver: 'Silver',
  Rating: '4.9 (121 trips)',
  Gas: 'Gas',
  View: 'View',
  Details: 'Details',
  car_Features:
    'AUX Input, Backup camera, Blind spot warning, Bluetooth, Heated seats, Sunroof, USB input.',
  Features: 'Features',
  Description: 'Description',
  Choose: 'Choose',
  car_Description:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur.',
    Monthly_plan:'Monthly plan',
    Select_monthly_plan: 'Select your monthly plan',
    Insurance_included: 'Insurance included. Change plans anytime.',
    Pay_you:'Pay as you go',
    five_hundred_Miles:'500 Miles',
    eight_five_zero:'850 Miles',
    one_two_zero:'1200 Miles',
    two_nine_four:'$294',
    four_six_nine:'$469',
    five_six_nine:'$569',
    six_six_nine:'$669',
month:'/month',
Auto_renews:'Auto-renews 200 miles at $0.45/mi',
four_five_Overage:'Overage miles: $0.45/mi',
three_five_Overage:'Overage miles: $0.35/mi',
two_five_Overage:'Overage miles: $0.25/mi',
Continue_to_schedule:'Continue to schedule',
Keys:"Keys",
General:'General',
Partnership_Benefits:'Partnership Benefits',
Support_Assistance:'Support and Assistance',
About_SwiftRide:'About SwiftRide',
}
